import type { CollectionConfig } from 'payload'

import { isAuthenticated } from '../../access/isAuthenticated'

// A prompt is a single nudge surfaced to the artist — generated by the
// trigger engine, optionally enriched with LLM-drafted copy, and resolved
// by the artist marking it done/dismissed/snoozed.
//
// Schema is intentionally loose: `payload` is a JSON blob carrying the
// kind-specific context (artwork slug, order id, gallery name, etc.) so
// adding a new trigger kind doesn't require a migration.
export const MarketingPrompts: CollectionConfig = {
  slug: 'marketing-prompts',
  admin: {
    group: 'Marketing',
    useAsTitle: 'title',
    defaultColumns: ['title', 'kind', 'status', 'urgency', 'createdAt'],
    description:
      'Nudges generated by the marketing trigger engine. The artist resolves them via the dashboard widget; this list is the full history.',
  },
  access: {
    create: isAuthenticated,
    read: isAuthenticated,
    update: isAuthenticated,
    delete: isAuthenticated,
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      admin: {
        description: 'Short one-line summary shown in the dashboard widget.',
      },
    },
    {
      name: 'kind',
      type: 'select',
      required: true,
      options: [
        { label: 'No new work', value: 'catalog_idle' },
        { label: 'Idle gallery', value: 'gallery_idle' },
        { label: 'Rotate hero', value: 'hero_rotate' },
        { label: 'Milestone', value: 'milestone' },
        { label: 'Top performer', value: 'top_performer' },
      ],
      index: true,
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'active',
      options: [
        { label: 'Active', value: 'active' },
        { label: 'Snoozed', value: 'snoozed' },
        { label: 'Dismissed', value: 'dismissed' },
        { label: 'Done', value: 'done' },
      ],
      index: true,
    },
    {
      name: 'urgency',
      type: 'select',
      required: true,
      defaultValue: 'normal',
      options: [
        { label: 'Low', value: 'low' },
        { label: 'Normal', value: 'normal' },
        { label: 'High', value: 'high' },
      ],
    },
    {
      name: 'body',
      type: 'textarea',
      admin: {
        description: 'Longer description shown when the artist expands the prompt.',
      },
    },
    {
      name: 'payload',
      type: 'json',
      admin: {
        description:
          'Kind-specific context (artwork slug, order id, gallery name, etc.). Used by the LLM draft endpoint and by snooze/dedupe logic.',
      },
    },
    {
      name: 'draftCopy',
      type: 'textarea',
      admin: {
        description:
          'LLM-generated draft caption. Empty until the artist clicks "draft me a post"; cached after so re-opening the modal is free.',
      },
    },
    {
      name: 'socialTarget',
      type: 'select',
      defaultValue: 'none',
      options: [
        { label: 'No target', value: 'none' },
        { label: 'Instagram', value: 'instagram' },
        { label: 'Facebook', value: 'facebook' },
        { label: 'Twitter', value: 'twitter' },
        { label: 'Pinterest', value: 'pinterest' },
        { label: 'Email newsletter', value: 'email' },
      ],
    },
    {
      name: 'relatedArtwork',
      type: 'relationship',
      relationTo: 'artworks',
      admin: {
        description:
          'Optional — the specific artwork this prompt references. Used by deep links and image attachments in drafts.',
      },
    },
    {
      name: 'snoozedUntil',
      type: 'date',
      admin: {
        condition: (data) => data?.status === 'snoozed',
        description: 'Status flips back to active automatically after this date.',
      },
    },
    {
      name: 'resolvedAt',
      type: 'date',
      admin: {
        readOnly: true,
        description: 'Auto-set when the artist marks the prompt done or dismissed.',
      },
    },
  ],
  hooks: {
    beforeChange: [
      ({ data, originalDoc }) => {
        // Stamp resolvedAt the first time status moves out of 'active'/'snoozed'.
        const wasOpen =
          !originalDoc?.status ||
          originalDoc.status === 'active' ||
          originalDoc.status === 'snoozed'
        const isClosed = data?.status === 'done' || data?.status === 'dismissed'
        if (wasOpen && isClosed && !data.resolvedAt) {
          data.resolvedAt = new Date().toISOString()
        }
        return data
      },
    ],
  },
  timestamps: true,
}
